export const categories = [
  { id: 'plumber', nameEn: 'Plumber', nameHi: 'प्लंबर', nameOr: 'ପ୍ଲମ୍ବର', isEmergency: true },
  { id: 'electrician', nameEn: 'Electrician', nameHi: 'इलेक्ट्रीशियन', nameOr: 'ଇଲେକ୍ଟ୍ରିସିଆନ୍', isEmergency: true },
  { id: 'carpenter', nameEn: 'Carpenter', nameHi: 'बढ़ई', nameOr: 'ବଡ଼ଇ', isEmergency: false },
  { id: 'mechanic', nameEn: 'Mechanic', nameHi: 'मैकेनिक', nameOr: 'ମେକାନିକ୍', isEmergency: true },
  { id: 'clinic', nameEn: 'Clinic/Doctor', nameHi: 'क्लिनिक/डॉक्टर', nameOr: 'କ୍ଲିନିକ୍/ଡାକ୍ତର', isEmergency: true },
  { id: 'pharmacy', nameEn: 'Pharmacy', nameHi: 'फार्मेसी', nameOr: 'ଫାର୍ମାସି', isEmergency: true },
];

export const workers = [
  {
    id: 'w1',
    displayName: 'Rakesh Plumber',
    phoneE164: '+919555000111',
    whatsappE164: '+919555000111',
    categoryId: 'plumber',
    languages: ['or', 'hi'],
    experienceYears: 6,
    isOnline: true,
    isVerified: true,
    trustScore: 86,
    ratingAvg: 4.6,
    ratingCount: 128,
    completedJobs: 410,
    localityLabel: 'Bhadrak Town',
    areaCoverageKm: 5,
    location: { lat: 21.0587, lng: 86.4958 },
    workingHoursLabel: '7am - 9pm',
    emergencyAvailable: true,
    status: 'available',
  },
  {
    id: 'w2',
    displayName: 'Suresh Electric Works',
    phoneE164: '+919555000222',
    whatsappE164: '+919555000222',
    categoryId: 'electrician',
    languages: ['or', 'en'],
    experienceYears: 9,
    isOnline: true,
    isVerified: true,
    trustScore: 91,
    ratingAvg: 4.8,
    ratingCount: 210,
    completedJobs: 610,
    localityLabel: 'Bhadrak Station Area',
    areaCoverageKm: 7,
    location: { lat: 21.0623, lng: 86.5051 },
    workingHoursLabel: '8am - 10pm',
    emergencyAvailable: true,
    status: 'available',
  },
  {
    id: 'w3',
    displayName: 'Kalinga Carpentry',
    phoneE164: '+919555000333',
    whatsappE164: '+919555000333',
    categoryId: 'carpenter',
    languages: ['or', 'hi'],
    experienceYears: 12,
    isOnline: false,
    isVerified: true,
    trustScore: 83,
    ratingAvg: 4.5,
    ratingCount: 76,
    completedJobs: 250,
    localityLabel: 'Charampa',
    areaCoverageKm: 6,
    location: { lat: 21.0502, lng: 86.5193 },
    workingHoursLabel: '9am - 7pm',
    emergencyAvailable: false,
    status: 'offline',
  },
  {
    id: 'w4',
    displayName: 'Sai Auto Garage',
    phoneE164: '+919555000444',
    whatsappE164: '+919555000444',
    categoryId: 'mechanic',
    languages: ['or', 'hi', 'en'],
    experienceYears: 8,
    isOnline: true,
    isVerified: false,
    trustScore: 72,
    ratingAvg: 4.2,
    ratingCount: 44,
    completedJobs: 130,
    localityLabel: 'Randia',
    areaCoverageKm: 10,
    location: { lat: 21.0419, lng: 86.4907 },
    workingHoursLabel: '9am - 8pm',
    emergencyAvailable: true,
    status: 'busy',
  },
  {
    id: 'w5',
    displayName: 'Maa Clinic',
    phoneE164: '+919555000555',
    whatsappE164: '+919555000555',
    categoryId: 'clinic',
    languages: ['or', 'hi'],
    experienceYears: 15,
    isOnline: true,
    isVerified: true,
    trustScore: 94,
    ratingAvg: 4.7,
    ratingCount: 312,
    completedJobs: 0,
    localityLabel: 'Bhadrak Bus Stand',
    areaCoverageKm: 3,
    location: { lat: 21.0581, lng: 86.5037 },
    workingHoursLabel: '24x7',
    emergencyAvailable: true,
    status: 'available',
  },
  {
    id: 'w6',
    displayName: 'Seba Pharmacy',
    phoneE164: '+919555000666',
    whatsappE164: '+919555000666',
    categoryId: 'pharmacy',
    languages: ['or', 'en'],
    experienceYears: 10,
    isOnline: true,
    isVerified: true,
    trustScore: 89,
    ratingAvg: 4.6,
    ratingCount: 198,
    completedJobs: 0,
    localityLabel: 'Bhadrak Market',
    areaCoverageKm: 4,
    location: { lat: 21.0599, lng: 86.4971 },
    workingHoursLabel: '8am - 11pm',
    emergencyAvailable: true,
    status: 'available',
  },
];
